# Generated by Django 4.0.1 on 2023-02-08 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarbonTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_specification', models.CharField(max_length=100)),
                ('a1_a3', models.IntegerField(null=True)),
                ('a4', models.IntegerField(null=True)),
                ('wf', models.IntegerField(null=True)),
                ('c2', models.IntegerField(null=True)),
                ('c3_c4', models.IntegerField(null=True)),
                ('c2_c4', models.IntegerField(null=True)),
                ('d', models.IntegerField(null=True)),
                ('total_a1_a5', models.IntegerField(null=True)),
                ('total_a_c', models.IntegerField(null=True)),
                ('a1', models.IntegerField(default='0.000', null=True)),
                ('a2', models.IntegerField(default='0.000', null=True)),
                ('a3', models.IntegerField(default='0.000', null=True)),
                ('a5', models.IntegerField(default='0.000', null=True)),
                ('b1', models.IntegerField(default='0.000', null=True)),
                ('b2', models.IntegerField(default='0.000', null=True)),
                ('b3', models.IntegerField(default='0.000', null=True)),
                ('b4', models.IntegerField(default='0.000', null=True)),
                ('b5', models.IntegerField(default='0.000', null=True)),
                ('c1', models.IntegerField(default='0.000', null=True)),
                ('c3', models.IntegerField(default='0.000', null=True)),
                ('c4', models.IntegerField(default='0.000', null=True)),
                ('tenant_id', models.IntegerField(default='0001', null=True)),
            ],
            options={
                'db_table': 'carbon_table',
            },
        ),
        migrations.CreateModel(
            name='ElementGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'element_group',
            },
        ),
        migrations.CreateModel(
            name='StructuralElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'structural_element',
            },
        ),
        migrations.CreateModel(
            name='Carbon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gia', models.IntegerField(null=True)),
                ('quantity', models.IntegerField(null=True)),
                ('carbon_table', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carbon', to='menu_items.carbontable')),
                ('element_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='menu_items.elementgroup')),
                ('substructural_element', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='menu_items.structuralelement')),
            ],
            options={
                'db_table': 'carbon',
            },
        ),
    ]
