# Generated by Django 4.0.1 on 2023-02-08 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carbontable',
            name='a1',
            field=models.DecimalField(blank=True, decimal_places=3, default='0.000', max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='carbontable',
            name='a1_a3',
            field=models.DecimalField(decimal_places=3, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='carbontable',
            name='a2',
            field=models.DecimalField(blank=True, decimal_places=3, default='0.000', max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='carbontable',
            name='a3',
            field=models.DecimalField(blank=True, decimal_places=3, default='0.000', max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='carbontable',
            name='a4',
            field=models.DecimalField(decimal_places=3, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='carbontable',
            name='a5',
            field=models.DecimalField(blank=True, decimal_places=3, default='0.000', max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='carbontable',
            name='b1',
            field=models.DecimalField(blank=True, decimal_places=3, default='0.000', max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='carbontable',
            name='b2',
            field=models.DecimalField(blank=True, decimal_places=3, default='0.000', max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='carbontable',
            name='b3',
            field=models.DecimalField(blank=True, decimal_places=3, default='0.000', max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='carbontable',
            name='b4',
            field=models.DecimalField(blank=True, decimal_places=3, default='0.000', max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='carbontable',
            name='b5',
            field=models.DecimalField(blank=True, decimal_places=3, default='0.000', max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='carbontable',
            name='c1',
            field=models.DecimalField(blank=True, decimal_places=3, default='0.000', max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='carbontable',
            name='c2',
            field=models.DecimalField(decimal_places=3, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='carbontable',
            name='c2_c4',
            field=models.DecimalField(decimal_places=3, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='carbontable',
            name='c3',
            field=models.DecimalField(blank=True, decimal_places=3, default='0.000', max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='carbontable',
            name='c3_c4',
            field=models.DecimalField(decimal_places=3, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='carbontable',
            name='c4',
            field=models.DecimalField(blank=True, decimal_places=3, default='0.000', max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='carbontable',
            name='d',
            field=models.DecimalField(decimal_places=3, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='carbontable',
            name='material_specification',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='carbontable',
            name='total_a1_a5',
            field=models.DecimalField(decimal_places=3, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='carbontable',
            name='total_a_c',
            field=models.DecimalField(decimal_places=3, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='carbontable',
            name='wf',
            field=models.DecimalField(decimal_places=3, max_digits=20, null=True),
        ),
    ]
